version: "3.8"

services:
  event_ticketing_website:
    build: .

    container_name: event_ticketing_website-app
    ports:
      - "4004:3000"
    restart: unless-stopped

    environment:
      - NODE_ENV=production

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
