name: Deploy to PROD of Timro Ticket User Panel
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PROD_SSH_KEY }}
      - name: Clone repository to PROD or Pull changes if already cloned
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PROD_HOST }} << 'EOF'
            if [ ! -d "/var/www/timroticket.com/.git" ]; then
              GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_timroticketuser" git clone -b production git@github.com:BandBTech/event_ticketing_website.git /var/www/timroticket.com
            else
              cd /var/www/timroticket.com
              GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_timroticketuser" git reset --hard
              GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_timroticketuser" git pull --rebase origin production
            fi
          EOF
      - name: Build and Deploy App on PROD
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PROD_HOST }} << 'EOF'
            cd /var/www/timroticket.com
            docker-compose down || true
            docker-compose up --build -d
            # Remove existing build folder
            rm -rf ./out
            # Get the container ID of the running container
            CONTAINER_ID=$(docker ps -q --filter "name=event_ticketing_website-app")
            # Copy the build folder from the container
            docker cp $CONTAINER_ID:/usr/share/nginx/html ./out
          EOF
